version: "3.8"
services:
  task-management:
    container_name: task_management_con
    image: task_management_img:v12.3
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: jdbc:mysql://mysql:3306/organizationdb
      DATASOURCE_PASSWORD: yourpassword
      DATASOURCE_USERNAME: root
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
    depends_on:
      - mysql
      - kafka

  mysql:
    container_name: mysql
    image: mysql
    restart: unless-stopped
    environment:
      DATABASE_HOST: docker-mysql
      DATABESE_PORT: 3306
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: organizationdb
      MYSQL_PASSWORD: yourpassword

  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper_container
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka_broker
    container_name: broker_container
    depends_on:
      - zookeeper
    restart: unless-stopped
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8081:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181